name: google_fonts
description: A package to include fonts from fonts.google.com.
version: 0.0.2
homepage: https://fonts.google.com/

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  mustache: ^1.1.1
  path_provider: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter